drivers: power: supply: battman_dbg: Fix unused result warning
drivers/power/supply/battman_dbg/somc_battman_dbg.c:78:2: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wun
used-result]
   78 |         kstrtoint(buf, 10, &bmdbg_dev->bmlog_timer);
      |         ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/power/supply/battman_dbg/somc_battman_dbg.c:104:2: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wu
nused-result]
  104 |         kstrtou64(buf, 0, &bmdbg_dev->bmlog_categories);
      |         ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/power/supply/battman_dbg/somc_battman_dbg.c:126:2: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wu
nused-result]
  126 |         kstrtou32(buf, 0, &bmdbg_dev->bmlog_level);
      |         ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/power/supply/battman_dbg/somc_battman_dbg.c:271:2: error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wu
nused-result]
  271 |         kstrtoint(buf, 10, &bmdbg_dev->regupdate_timer);
      |         ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I8320aba42b6fa8e6ee3b7679223b583d56fbbdad
Signed-off-by: jmpfbmx <jmpf.bmx@gmail.com>